name: Rust (Wasm-Pack)

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  wasm-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Wasm-Pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install Firefox
        run: sudo apt-get install -y firefox
      - name: Run Wasm-Pack Tests
        run: wasm-pack test --headless --firefox
